### ISSUE TITLE
[feature request]Hot reloading support

### ISSUE THREAD

**Issue by douglarek** [megaease/easeprobe#69] opened 2022-05-05 09:16 UTC
**Background & X Problem**
Currently (2022-05-05), easeprobe does not support hot reloading, so the problem is that if I just modify the config.yaml file (which can be a frequent action), then I need to restart the application for it to take effect.

**Proposal and Expectation**
We can add a reload option to the configuration file to enable it:

```yaml
reload:
  enabled: true # default is false
  period: 10s # scan interval, default is 10s
```

**Solutions & Y Problems**
We need to not lose the SLA information that the configuration has not changed when the reload is turned on.

**Comment by proditis** [comment] 2022-05-05 11:07
Hi @douglarek and @haoel I may have an alternative suggestion for this, not sure if this also satisfies your original requirements, but it may be better if we did this through a signal handler (eg SIGHUP). It will also be much simpler to implement (i think)?

Having the application reread the configuration all the time without an admin intervention is a bit dangerous imho. I much rather have control of when the application re-reads its configuration.

What do you think?

**Comment by haoel** [comment] 2022-05-05 12:03
Actually, I thought this feature a couple of weeks ago.

To accomplish this feature, We need to do understand how we change the prober's configuration and keep the SLA statistics. 

There are several works need to do

0) Detect the configuration file changes or just handle a signal likes @proditis mentioned above.

1) We need a uniq identity for each prober, so that we can do add, delete, and update operations. Maybe we can reuse the name of prober to do this(back compatibility)

2) We can put the SLA statistics into a dedicated map[probe-name, SLA]. Then, we can simply destroy all of probes and recreate all probers. This need a bit more refactoring. 

For notifications configuration changes, just destroy and recreate all of them.

But we need to know the SLA is still stored in memory, I am thinking about persistent them, if we persistent that, we can free to restart the EaseProbe.

I quite like to persistent the SLA statistics into a file. How do you guys think?

- Hao

**Comment by haoel** [comment] 2022-05-05 12:10
@douglarek I think the X-problem of this feature should be that keep the SLA statistics after the process restart, and the Y-Problem is reloading the configuration without exiting the process. Right?

-- Hao

**Comment by proditis** [comment] 2022-05-05 12:18
@haoel I agree, having the SLA statistics persist into a file will solve more than just this problem :smiley: (such as restarts for updating the actual easeprobe binary)

**Comment by douglarek** [comment] 2022-05-05 14:41
> @douglarek I think the X-problem of this feature should that keep the SLA statistics after the process restart, and the Y-Problem is reloading the configuration without exiting the process.
> 
> Am I Right? ;-)
> 
> -- Hao

totally agree.

**Comment by haoel** [comment] 2022-05-07 03:41
# Design

### Data structure
```
  ┌──────┐    ┌──────┐       ┌──────┐
  │prober│    │prober│       │prober│
  ├──────┤    ├──────┤  .....├──────┤
  │Result│    │Result│       │Result│
  └───▲──┘    └──▲───┘       └───▲──┘
      │          │               │
      │          │ref            │
      │ref   ┌───┴────────────┐  │ref
      └──────┤    KV Store    ├──┘
             │ <Name, Result> │
             └────────────────┘
                probe/data.go

                   │    ▲
                   ▼    │

            $CWD/data/data.yaml
       ( config - settings.sla.data )

```

### Process

```
                               Remove probe data
   Read Data                    that is not in
   from file                      config file
   ┌──────┐     ┌──────────────┐   ┌───────┐     ┌──────┐
   │ Load ├─────►Config Probers├───► Clean ├─────► Save │
   └──────┘     └──────────────┘   └───────┘     └──────┘
  initData()     configProber()    CleanData()   saveData()
 conf/conf.go       main.go       probe/data.go   main.go
```

### Graceful Shutdown

```
                                                          configProbers()
                                                             main.go
                                                         ┌──► prober A
                                             ┌─────────┐ │
                        1)exit all probers ─►│doneProbe├─┼──► Prober B
                                             └─────────┘ │
 SIGTERM     ┌────┐     2)wait probers exit    channel   └──► Prober C
 SIGINT  ──► │done├──►                       ┌─────────┐
             └────┘     3)exit the watch ───►│doneWatch├────► Watch & Notify
             channel                         └─────────┘       watchEvent()
                        4)exit the save        channel           main.go
                                   │         ┌────────┐
                                   └────────►│doneSave├─────► Save the Data
                                             └────────┘         saveData()
                                               channel            main.go
```

**Comment by haoel** [comment] 2022-05-08 01:27
@douglarek the PR has been merged, could you please have a try?

**Comment by douglarek** [comment] 2022-05-09 01:41
> @douglarek the PR has been merged, could you please have a try?

thanks, i will have a try

**Comment by douglarek** [comment] 2022-05-09 06:44
> @douglarek the PR has been merged, could you please have a try?

I have tested it in my internal k8s cluster, it works fine. 
A little more thought: should we have a data.yml cleanup strategy ? I found it would keep all old data.yml as this:

```
$ ls data/
data.yaml  data.yaml-2022-05-09T14:37:32+08:00  data.yaml-2022-05-09T14:41:05+08:00
```

Or should we keep all history files ?

thanks.

**Comment by haoel** [comment] 2022-05-09 07:45
@douglarek 

Yes, I do this on purpose. 

The reason is that I don't know how many historical files we need to keep, and the file is so small only created when Easeproce is restarted, so it's ok to keep all history, we know, Linux ext4 fs supports 2^32 files in one directory. So, it won't impact anything. 

And I agree with you, those historical files might be too much in the future, probably, it's fine we can just keep a few of them. 

So, do you want to do some code work to help on this ?

-- Hao

**Comment by douglarek** [comment] 2022-05-09 08:08
> @douglarek
> 
> Yes, I do this on purpose.
> 
> The reason is that I don't know how many historical files we need to keep, and the file is so small only created when Easeproce is restarted, so it's ok to keep all history, we know, Linux ext4 fs supports 2^32 files in one directory. So, it won't impact anything.
> 
> And I agree with you, those historical files might be too much in the future, probably, it's fine we can just keep a few of them.
> 
> So, do you want to do some code work to help on this ?
> 
> -- Hao

Thank you for detailing the goal. Considering that restarting is not a high-frequency operation, and the k8s instance will drift to different nodes after being restarted, its size and number should not be a big problem, maybe it can be put on hold.

**Comment by proditis** [comment] 2022-05-09 08:26
I believe this should be configurable somehow, something like `history: true` maybe?

This way we dont put another task on the sysadmins shoulders :partying_face:, to clean up and monitor these files. 

If you agree I will take a look later today to see if i can figure out how to make this change :smiley: 

PS: @haoel now that this feature is in `main` should I open another issue for this particular change?

**Comment by haoel** [comment] 2022-05-09 08:29
@proditis Cool! You can do anything you like!

**Comment by haoel** [comment] 2022-05-15 07:21
#81  merged. @douglarek please have a try！

**Comment by proditis** [comment] 2022-05-16 18:58
@haoel I did a quick test and i noticed two small issues

1) I tested with the following configuration snippet
```yaml
  sla:
    backups: 20
    schedule : "daily"
    time: "23:59"
    debug: false
```
running easeprobe in the foreground and although easeprobe creates the `data/data.yaml` when it starts. It never gets rotated with SIGHUP.

Setting the `data: data.yaml` creates rotations as expected.

I think that if there is no `data:` key for `sla:` then maybe we should skip the creation of `data.yaml` altogether? 

2. I wanted to create the `data.yaml` file on the current folder (no subfolders), so i added `data: ./data.yaml` but the file got created as `data/data.yaml`. In fact there is no way to define an absolute path for `data.yaml` without having a `/data/` folder being injected between (eg a setting of `data: /tmp/data.yaml` created a file `/tmp/data/data.yaml`)

**Comment by haoel** [comment] 2022-05-17 01:01
@proditis my response as below.

1. The `self-rotate` default value is `false`, and the `data` default is `data.yaml`, so the behavior of `SIGHUP` just simply closes `data.yaml` and opens the `data.yaml`, because the `logrotate` would rename the `data.yaml` to a backup. if the outside program only sends the HUP but no rename, it looks like nothing happened. 

And the `backups` are ignored if `self_rotate: false`.  if you configure the `self_rotate: true`, then EaseProbe would rename the data file. and if the `self_rotate: false`.

I tested your configuration, it works as expected. Please verify it again.
(p.s. I mannally run the logroate : `logrotate --force /etc/logrotate.conf`)


2. The reason for using a dedicated `data` directory is the high availability architecture. For example, we usually mount a distributed filesystem to store the important data,  or when we run the EaseProbe on the kubernetes, we can create the PV/PVC for this directory and mount it to K8s Pod, so that EaseProbe can be deployed to any nodes.  I think this is the best practice, I just enable it as the default behavior.

Using the absolute path also is a best practice, because it is consistent. The relative path is not. because the program could be run by shell command, or systemd, or sysvinit, so, the relative path could be a different place. 

I cannot understand why we cannot configure the absolute path. could you please tell me more?

**Comment by haoel** [comment] 2022-05-17 07:41
Sorry, I mixed up the log and the data file. the above message is wrong, the `data.yaml` won't rotate, because it is not an appended file. the size is consistent.

**Comment by proditis** [comment] 2022-05-17 08:59
@haoel Thank you for the excellent explanations once again

2. this was my understand of how it worked, it was clearly wrong :smile: I will update my tests to reflect that

3. Let me clarify this a bit more. I agree with your statement that using absolute path should be encouraged, however i couldnt make easprobe to actually use that absolute path. 
I added this `data: /tmp/data.yaml` to my configuration. The location for the `data.yaml` should be `/tmp/data.yaml` but instead easeprobe converts it to **`/tmp/data/data.yaml`** (_notice the `/data/` folder between `/tmp/` and `data.yaml`_ check https://github.com/megaease/easeprobe/blob/main/conf/conf.go#L290)

I hope this helps.

**Comment by haoel** [comment] 2022-05-17 09:14
Finally, I understand the case! Thank you @proditis !

The problem is that I keep adding the `data` directory! this definitely is a bug!  I mixed the scenarios.  

- **Case One**: No data file configured, then we use the `$CWD/data/date.yaml` as the default.
- **Case Two**: data file name configured, but not configured the directory, such as: `mydatafile.yaml`, we use the `$CWD/data/mydatafile.yaml`
- **Case Three**: the full path has been configured. we just simply use the full path.
- **Case Four**: the disable flag configured - `data : - `, then we disable the data file.

So, the code logic should be:

```
if datafile == `-` then return
dir, file := filepath.split(datafile)
if dir == "" then dir = filepath.join( getcwd(), "data")
if file == "" then file = `data.yaml`

filepath.join(dir, file)
```

**Comment by proditis** [comment] 2022-05-18 18:24
@haoel I think that this issue is resolved and we can safely close it. The features requested where all implemented and confirmed as working by the original poster and I.

**Comment by haoel** [comment] 2022-05-19 08:38
Close this issue!

**Closed by haoel** 2022-05-19 08:38 UTC
Labels: enhancement
